Handle large message downloads over http.
7theta/via pull request #14
Opened 2020-10-07 22:33 UTC by tom7t

2020-10-11 13:20 UTC, sandhu requested changes

2020-10-11 13:20 UTC, sandhu commented on src/via/authenticator.clj
> +          (assoc user :token (jwt/encrypt (assoc user :exp (t/+ (t/now) (t/new-duration expiry :hours)))
`clj-time` is already being used - https://github.com/7theta/via/blob/master/src/via/authenticator.clj#L88

Since it's deprecated, suggest migrating that use to `tick` as well and removing `clj-time` as a dependency

2020-10-11 13:20 UTC, sandhu commented on src/via/defaults.cljc
> +(def protocol-version "2")
Can this be a number (double) so that we can do < and > comparisons ?

2020-10-11 13:20 UTC, sandhu commented on src/via/endpoint.clj
> +           max-ws-v1 (* 4 1024 1024)
I wouldn't bother with this as API option. We already know the limit and the goal is to migrate v1 clients anyway.

2020-10-11 13:20 UTC, sandhu commented on src/via/endpoint.clj
> +            (send-to-channel! channel (encode {:type :download :payload payload})))
The download operation should include a URL. That will allow us to use a CDN transparently in the future.

2020-10-11 13:20 UTC, sandhu commented on src/via/endpoint.clj
> +      (when (try
This needs to handle a couple of scenarios:
400 - Token is missing
403 - Token is invalid
410 - Token is valid, but expired
200 - GTG, here's the content

2020-10-11 13:20 UTC, sandhu commented on src/via/endpoint.clj
> +             (println e "Error occurred in downloads audit future."))))))
Suggest printing the exception after the message.

2020-10-11 13:20 UTC, sandhu commented on src/via/endpoint.cljs
> +                  :download-url (-> url
URL should be obtained from the message

2020-10-11 13:20 UTC, sandhu commented on src/via/endpoint.cljs
> +      (j/call :then handle-message)
Think we have a race condition here.

1. Initial message sent for a sub is huge - download gets triggered
2. While the download is taking place async, the sub gets updated on the remote side
3. Via computes a diff and sends the patch
4. Patch arrives before download is finished

2020-10-11 13:20 UTC, sandhu commented on src/via/endpoint.clj
> +
Also some kind of sequence number as a way to deal with the race condition described below.

2020-10-11 15:43 UTC, tom7t commented on src/via/authenticator.clj
> +          (assoc user :token (jwt/encrypt (assoc user :exp (t/+ (t/now) (t/new-duration expiry :hours)))
Confused. This is the line you've mentioned. clj-time has also been removed as a dependency in project.clj as part of this PR.

2020-10-11 15:43 UTC, tom7t commented on src/via/defaults.cljc
> +(def protocol-version "2")
Will do.

2020-10-11 15:45 UTC, tom7t commented on src/via/endpoint.cljs
> +      (j/call :then handle-message)
Ah, good catch. Will think about some sort of sequence number as you mentioned below.

2020-10-11 15:45 UTC, tom7t commented on src/via/endpoint.clj
> +            (send-to-channel! channel (encode {:type :download :payload payload})))
Will do.

2020-10-11 15:45 UTC, tom7t commented on src/via/endpoint.clj
> +      (when (try
Will do.

2020-10-11 15:47 UTC, tom7t commented on src/via/endpoint.clj
> +           max-ws-v1 (* 4 1024 1024)
That's fair. I was thinking this would provide the option to take advantage of v2 even while v1 clients are updating over time, in the event where there are several thousand clients out in the wild updating over time. But we can instead of just set the default max-ws to be 4mb, and the API consumers can configure something smaller as they see fit (which should be done when the majority of clients are v2, so that we send less massive messages over ws and more over http).

2020-10-11 15:49 UTC, sandhu commented on src/via/authenticator.clj
> +          (assoc user :token (jwt/encrypt (assoc user :exp (t/+ (t/now) (t/new-duration expiry :hours)))
Sorry. My mistake.

2020-10-11 15:53 UTC, sandhu commented on src/via/endpoint.clj
> +           max-ws-v1 (* 4 1024 1024)
I think the option of sending 4m to v1 clients is fine. Just didn't think we should expose it as an option.

2020-10-13 14:01 UTC, tom7t commented on src/via/endpoint.clj
> +            (send-to-channel! channel (encode {:type :download :payload payload})))
After offline discussion, will wait to include this feature in a future update.

2020-10-13 16:17 UTC, tom7t commented on src/via/endpoint.cljs
> +      (j/call :then handle-message)
Sequence number added for subs as :sn key for sub messages.

2020-10-13 16:18 UTC, tom7t commented on src/via/endpoint.clj
> +
Added here: https://github.com/7theta/via/pull/14/files#diff-10249caebfbfe17eee07b31f16b4c4c83ac5c2cf6c04cd24b425e7357e4d3dddR76

2020-10-13 17:22 UTC, ct7t commented on example/src/via/example/subs.clj
> +              (Thread/sleep 30000)
Any concerns about this being hardcoded?  Should it be parameterized?

2020-10-15 11:42 UTC, merged